node {
    def jdk
    def dockerArguments= '--user=root'
    def pipFreezeOutput
    def pipShowOutput
    def pythonImage = "python:${params.PYTHON_VERSION}-slim"
    def gitRepoWithRequirements = "${params.REQUIREMENTS_GIT_REPO}"
    def gitRepoWithRequirementsBranch = "${params.REQUIREMENTS_GIT_BRANCH}"
    final VULNERABLE_RETURN_CODE = "2"

    stage('Fetch Pretender pip script') { // for display purposes
        // Get some code from a GitHub repository
        dir('core') {
            git  branch: 'main', url:'https://github.com/zvigrinberg/rhda-pipelines-examples.git'
        }
    }

    stage('Checkout Git Repo') { // for display purposes
        // Get some code from a GitHub repository
        dir('requirementsDir') {
            git  branch: gitRepoWithRequirementsBranch, url: gitRepoWithRequirements
        }



    }

    stage('Install Python Package') {
        docker.withTool('docker-tool') {
            docker.withServer('tcp://localhost:2376','docker-server-certs'){

                docker.image(pythonImage).inside(dockerArguments) {
                    sh 'pip install -r requirementsDir/requirements.txt'
                    pipFreezeOutput = sh(script: "pip freeze --all" ,returnStdout: true ).trim()
                    writeFile([file: 'pip-freeze.txt', text: pipFreezeOutput])
                    pipFreezeOutput = sh(script: "pip freeze --all | awk -F \"==\" '{print \$1}' | tr \"\n\" \" \"" ,returnStdout: true ).trim()
                    pipShowOutput = sh(script:"pip show ${pipFreezeOutput}" ,returnStdout: true )
                    writeFile([file: 'pip-show.txt', text: pipShowOutput])


                }
            }
        }
    }
    stage('RHDA Run Analysis') {
        echo "pipFreezeOutput= ${pipFreezeOutput}"
        echo "pipShowOutput= ${pipShowOutput}"
        def rhdaWorkspace = env.WORKSPACE
        escapedWorkspace = rhdaWorkspace.toString().replaceAll(" ", "\\\\ ")
        echo "escapedWorkspace= ${escapedWorkspace}"
        def doubleEscapedWorkspace = escapedWorkspace.replaceAll("\\\\","\\\\\\\\").replaceAll("\\/","\\\\/")
        echo "doubleEscapedWorkspace= ${doubleEscapedWorkspace}"
// sh(script: "echo ${escapedWorkspace} | sed 's/\\/\\\\/g' | sed 's/\//\\\//g'" ,returnStdout: true ).trim()
        sh "sed 's/\$PLACE_HOLDER/${doubleEscapedWorkspace}/g' core/python-pip/using-mock-script/pythonMock.sh > /tmp/pip ; chmod +x /tmp/pip"
        echo "escapedWorkspace= ${escapedWorkspace}"
        withEnv(["WORKSPACE_PATH=${escapedWorkspace}","EXHORT_PIP3_PATH=/tmp/pip","EXHORT_PYTHON3_PATH=/tmp/pip"]) {

            def result = rhdaAnalysis consentTelemetry: true, file: "${WORKSPACE}/requirementsDir/requirements.txt"
            if(result.trim().equals(VULNERABLE_RETURN_CODE) ) {
                unstable(message: "There are some vulnerabilities in Manifest, please upgrade according to the report")
            }
        }

    }

    stage('Clean Workspace') {
        cleanWs cleanWhenAborted: false, cleanWhenFailure: false, cleanWhenNotBuilt: false, cleanWhenUnstable: false
    }

}

